[dlg ModMenuName]
Amicitia Mod Menu[w][e]

[sel ModMenu]
[s]Player[f 4 26 0 184][e]
[s]Battle Select[f 4 26 1 185][e]
[s]Teleport[f 4 26 2 186][e]
[s]Sound Test[f 4 26 3 187][e]
[s]Field Select[f 4 26 4 188][e]
[s]Event Select[f 4 26 5 189][e]
[s]Camera[f 4 26 6 190][e]
[s]NPCs[f 4 26 7 191][e]
[s]Flags[f 4 26 8 192][e]
[s]Calendar[f 4 26 9 193][e]
[s]Movie Select[f 4 26 10 194][e]
[s]Check Phone/Auto Recover[f 4 26 11 195][e]
[s]About[f 4 26 12 196][e]

[dlg GENERIC_HELP_184]
[s]Edit Personas, items,[n]stats, money, or[n]even your name.[e]

[dlg GENERIC_HELP_185]
[s]Choose a battle type[n]to start, then begin[n]fighting![e]

[dlg GENERIC_HELP_186]
[s]Clip through walls and[n]explore out of bounds.[n][clr 18]□ button[clr 0] to change axis.[e]

[dlg GENERIC_HELP_187]
[s]Enter a BGM ID to[n]play an audio track.[e]

[dlg GENERIC_HELP_188]
[s]Enter a Field ID[n]and warp to the map.[e]

[dlg GENERIC_HELP_189]
[s]Enter an Event ID[n]to start an event.[e]

[dlg GENERIC_HELP_190]
[s]Change the camera's[n]position, rotation, and[n]field of view.[e]

[dlg GENERIC_HELP_191]
[s]Spawn NPC models &[n]play their animations.[e]

[dlg GENERIC_HELP_192]
[s]Toggle the various[n]values in the[n]game's memory.[e]

[dlg GENERIC_HELP_193]
[s]Set a date and time &[n]travel directly to it.[e]

[dlg GENERIC_HELP_194]
[s]Play a movie file, such[n]as one of the[n]animated cutscenes.[e]

[dlg GENERIC_HELP_195]
[s]View IM messages[n]or auto heal party.[e]

[dlg GENERIC_HELP_196]
[s]Show some info about[n]the development of[n]this mod.[e]

[dlg PlayerMenuName]
Player Options[w][e]

[sel PlayerMenu]
[s]Personas[f 4 26 0 199][e]
[s]Social Stats[f 4 26 1 200][e]
[s]Items[f 4 26 2 201][e]
[s]Set Confidant Rank[f 4 26 3 202][e]
[s]Set Protag Name[f 4 26 4 203][e]
[s]Set Team Name[f 4 26 5 204][e]
[s]Animation Test[f 4 26 6 205][e]
[s]Set Scale[f 4 26 7 206][e]
[s]Attach Item Model[f 4 26 8 207][e]
[s]Max Money[f 4 26 9 208][e]
[s]Max Level[f 4 26 10 209][e]
[s]Max HP/SP[f 4 26 10 210][e]

[dlg GENERIC_HELP_199]
[s]Add or remove your[n]Personas, or give party[n]members new Skills.[e]

[dlg GENERIC_HELP_200]
[s]Add points to Guts,[n]Knowledge, Proficiency,[n]Charm or Kindness.[e]

[dlg GENERIC_HELP_201]
[s]Give yourself any armor,[n]costumes, weapons,[n]key items etc.[e]

[dlg GENERIC_HELP_202]
[s]Select a Confidant and[n]set your current rank[n]with their Arcana.[e]

[dlg GENERIC_HELP_203]
[s]Rename the protag[n]at any point in[n]the game.[e]

[dlg GENERIC_HELP_204]
[s]Change the name of[n]the Phantom Thieves[n]at any point ingame.[e]

[dlg GENERIC_HELP_205]
[s]Play the protag's[n]Field GAP animations.[e]

[dlg GENERIC_HELP_206]
[s]Change the size of the[n]player's model.[e]

[dlg GENERIC_HELP_207]
[s]Enter an item's model[n]ID to attach it to[n]the protag's hand.[e]

[dlg GENERIC_HELP_208]
[s]Adds 9,999,999 yen[n]to your wallet.[e]

[dlg GENERIC_HELP_209]
[s]Makes all party[n]members Level 99.[e]

[dlg GENERIC_HELP_210]
[s]Sets everyone's HP and SP to 999.[e]

[dlg ItemMenuName]
Select Item Type...[w][e]

[sel ItemMenu]
Consumables[f 4 26 0 213][e]
Accessories[f 4 26 1 214][e]
Key Items[f 4 26 2 215][e]
Ranged Weapons[f 4 26 3 216][e]
Melee Weapons[f 4 26 4 217][e]
Outfits[f 4 26 5 218][e]
Armor[f 4 26 6 219][e]
Materials[f 4 26 7 220][e]
Skill Cards[f 4 26 8 221][e]

[dlg GENERIC_HELP_213]
[s]Items that recover HP[n]& SP, relieve ailments,[n]or buff/debuff.[e]

[dlg GENERIC_HELP_214]
[s]Items for your party[n]members to equip for[n]stat enhancements.[e]

[dlg GENERIC_HELP_215]
[s]Passive items that are[n]acquired throughout the[n]story.[e]

[dlg GENERIC_HELP_216]
[s]Arms that party members[n]can equip to fire[n]bullets during battle.[e]

[dlg GENERIC_HELP_217]
[s]Weapons used for basic[n]physical attacks[n]during battle.[e]

[dlg GENERIC_HELP_218]
[s]Appearance changes for[n]party members in[n]the Metaverse.[e]

[dlg GENERIC_HELP_219]
[s]Equippable items that[n]can boost defense or[n]provide benefits.[e]

[dlg GENERIC_HELP_220]
[s]Items that can be sold[n]to Iwai or used[n]to create tools.[e]

[dlg GENERIC_HELP_221]
[s]Items that can be used[n]to assign Skills[n]to your Personas.[e]

[dlg CommuMenuName]
Select Confidant...[w][e]

[sel CommuMenu]
Igor[f 4 26 0 224][e]
Morgana[f 4 26 1 225][e]
Makoto Niijima[f 4 26 2 226][e]
Haru Okumura[f 4 26 3 227][e]
Yusuke Kitagawa[f 4 26 4 228][e]
Sojiro Sakura[f 4 26 5 229][e]
Ann Takamaki[f 4 26 6 230][e]
Ryuji Sakamoto[f 4 26 7 231][e]
Goro Akechi[f 4 26 8 232][e]
Futaba Sakura[f 4 26 9 233][e]
Chihaya Mifune[f 4 26 10 234][e]
Caroline and Justine[f 4 26 11 235][e]
Munehisa Iwai[f 4 26 12 236][e]
Tae Takemi[f 4 26 13 237][e]
Sayado Kawakami[f 4 26 14 238][e]
Ichiko Ohya[f 4 26 15 239][e]
Shinya Oda[f 4 26 16 240][e]
Hifumi Togo[f 4 26 17 241][e]
Yuuki Mishima[f 4 26 18 242][e]
Toranosuke Yoshida[f 4 26 19 243][e]
Sae Niijima[f 4 26 20 244][e]
Kasumi Yoshizawa[f 4 26 21 245][e]
Takuto Maruki[f 4 26 22 246][e]
Sumire Yoshizawa[f 4 26 23 247][e]

[dlg GENERIC_HELP_224]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Fool[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_225]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Magician[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_226]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Priestess[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_227]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Empress[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_228]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Emperor[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_229]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Heirophant[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_230]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Lovers[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_231]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Chariot[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_232]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Justice[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_233]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Hermit[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_234]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Fortune[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_235]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Strength[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_236]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Hanged Man[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_237]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Death[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_238]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Temperance[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_239]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Devil[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_240]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Tower[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_241]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Star[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_242]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Moon[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_243]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Sun[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_244]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Judgement[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_245]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]World[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_246]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Faith[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_247]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Councillor[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_248]
[s]Set the desired rank[n]for the Confidant of[n]the [clr 9]Faith[clr 0][n]Arcana.[e]

[dlg StatsMenuName]
Select Stat Type...[w][e]

[sel StatsMenu]
Knowledge[f 4 26 0 251][e]
Charm[f 4 26 1 252][e]
Proficiency[f 4 26 2 253][e]
Guts[f 4 26 3 254][e]
Kindness[f 4 26 4 255][e]

[dlg GENERIC_HELP_251]
[s]Increase your[n][clr 26]Knowledge[clr 0] stat by[n]a number of points.[e]

[dlg GENERIC_HELP_252]
[s]Increase your[n][clr 26]Charm[clr 0] stat by[n]a number of points.[e]

[dlg GENERIC_HELP_253]
[s]Increase your[n][clr 26]Proficiency[clr 0] stat by[n]a number of points.[e]

[dlg GENERIC_HELP_254]
[s]Increase your[n][clr 26]Guts[clr 0] stat by[n]a number of points.[e]

[dlg GENERIC_HELP_255]
[s]Increase your[n][clr 26]Kindness[clr 0] stat by[n]a number of points.[e]

[dlg StatPrompt [Stats]]
Add how many points?[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg ItemPrompt [Items]]
Enter the item ID you want.[n](max. 4 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg ItemPrompt2 [Items]]
Enter how many items you want.[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg CmmDialog [Confidant Rank]]
Enter the Confidant's Arcana ID.[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg CmmDialog2 [Confidant Rank]]
Enter the desired Confidant rank.[w][e]

[dlg AnimMenuName]
Player Animation[w][e]

[sel AnimMenu]
Field Animation Test[e]
Morgana Out of Bag[e]
Morgana In Bag[e]
Show Bag[e]
Hide Bag[e]
Umbrella On[e]
Umbrella Off[e]

[dlg GAPMenuName]
GAP Playback[w][e]

[sel GAPMenu]
Set GAP ID[f 4 26 0 265][e]
Set GAP Index[f 4 26 1 266][e]
Toggle Loop[f 4 26 2 267][e]
Set Speed[f 4 26 3 268][e]
Set Time[f 4 26 4 269][e]
Playback animation[f 4 26 5 270][e]

[dlg GENERIC_HELP_265]
[s]Input the filename of[n]a [clr 9]field GAP file for[clr 0][n]this character. (Starts with [clr 9]af[clr 0])[e]

[dlg GENERIC_HELP_266]
[s]Input the index of the[n]animation from the [clr 26]GAP[clr 0][n]that you want to view.[e]

[dlg GENERIC_HELP_267]
[s]Decide whether you want[n]the animation to repeat or not[n]when it's finished.[e]

[dlg GENERIC_HELP_268]
[s]Decide the playback speed[n]of the animation.[e]

[dlg GENERIC_HELP_269]
[s]Decide how many seconds you[n]would like to play the[n]animation for.[e]

[dlg GENERIC_HELP_270]
[s]Execute the animation playback[n][clr 9]after the above settings[clr 0][n]have been completed.[e]

[dlg ScalePrompt [Scale Model]]
Set the character's model scale.[n]([clr 2]○ button[clr 0] to end)[n]Default is 10.[w][e]

[dlg CameraMenuName]
Camera Options[w][e]

[sel CameraMenu]
Reposition Camera[f 4 26 0 274][e]
Adjust FOV[f 4 26 1 275][e]
Adjust Zoom[f 4 26 2 276][e]
Rotate Camera[f 4 26 3 277][e]
Unlock Camera[f 4 26 4 278][e]
Lock Camera[f 4 26 5 279][e]
Disable Camera Shake[f 4 26 6 280][e]

[dlg GENERIC_HELP_274]
[s]Move the camera by[n]the X, Y or Z axis.[n][clr 18]□ button[clr 0] to change axis.[e]

[dlg GENERIC_HELP_275]
[s]Adjust the camera's[n]Field of View.[e]

[dlg GENERIC_HELP_276]
[s]Zoom the camera in[n]and out.[e]

[dlg GENERIC_HELP_277]
[s]Change the camera[n]orientation with[n]the D-pad.[e]

[dlg GENERIC_HELP_278]
[s]Make the camera[n]follow the player[n]again if locked.[e]

[dlg GENERIC_HELP_279]
[s]Stops the camera[n]from moving, which is[n]required to edit it.[e]

[dlg GENERIC_HELP_280]
[s]Stops the camera[n]from swaying slightly.[e]

[dlg CalendarMenuName]
Calendar Options[w][e]

[sel CalendarMenu]
Set Next Day[f 4 26 0 283][e]
Call Calendar[f 4 26 1 284][e]
Set Weather[f 4 26 2 285][e]
Loop Current Day[f 4 26 3 286][e]
Go to 3rd Semester[f 4 26 4 287][e]

[dlg GENERIC_HELP_283]
[s]Choose day & month[n]to warp to.[e]

[dlg GENERIC_HELP_284]
[s]End current day &[n]warp to the next[n]specified day.[e]

[dlg GENERIC_HELP_285]
[s]Change the weather[n]condition. Reload field[n]to see results.[e]

[dlg GENERIC_HELP_286]
[s]Choose the next time[n]of day to set after[n]current day ends.[e]

[dlg GENERIC_HELP_287]
[s]Go to first day of[n]new Royal content.[e]

[dlg CalendarPrompt[Calendar]]
Choose what month to start in.[n]([clr 2]○ button[clr 0] to end)[w][e]

[dlg CalendarPrompt2 [Calendar]]
Choose what day to start on.[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg EventDlg [Event Select]]
Choose the first 3 digits of
[n]the event to load.[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg EventDlg2 [Event Select]]
Choose the last 3 digits of
[n]the event to load.[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg KfEventDlg [KeyFree Event Select]]
Choose the first 3 digits of
[n]the KeyFree event to load.[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg KfEventDlg2 [KeyFree Event Select]]
Choose the last 3 digits of
[n]the KeyFree event to load.[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg FieldDlg [Field Select]]
Choose the first 3 digits of
[n]the field to load.[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg FieldDlg2 [Field Select]]
Choose the last 3 digits of
[n]the field to load.[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg SpawnMenuName]
NPC Options[w][e]

[sel SpawnMenu]
Spawn Model[f 4 26 0 298][e]
Animate Model[f 4 26 1 299][e]
Set Model Scale[f 4 26 2 300][e]
Attach Item Model[f 4 26 3 301][e]
Spawn Object Model[f 4 26 4 302][e]

[dlg GENERIC_HELP_298]
[s]Input a [clr 9]GMD filename[clr 0][n]to spawn a character[n]model from.[e]

[dlg GENERIC_HELP_299]
[s]Apply field animations[n]to the last NPC you[n]spawned.[e]

[dlg GENERIC_HELP_300]
[s]Set the scale of the[n]NPC model.[e]

[dlg GENERIC_HELP_301]
[s]Input a [clr 9]GMD filename[clr 0][n]to attach to the NPC.[e]

[dlg GENERIC_HELP_302]
[s]Input a [clr 9]GMD filename[clr 0][n]of an object to[n]spawn.[e]

[dlg PersonaMenuName]
Persona Options[w][e]

[sel PersonaMenu]
Add Persona[f 4 26 0 305][e]
Delete Personas[f 4 26 1 306][e]
Add Skill[f 4 26 2 307][e]
Unlock Full Compendium[f 4 26 3 308][e]
Evolve Persona[f 4 26 4 309][e]

[dlg GENERIC_HELP_305]
[s]Input Persona name/ID[n]to add to your stock.[e]

[dlg GENERIC_HELP_306]
[s]Permanently remove[n]all Personas from[n]your current stock.[e]

[dlg GENERIC_HELP_307]
[s]Choose party member &[n]add a Skill to[n]their current Persona.[e]

[dlg GENERIC_HELP_308]
[s]Register all Personas[n]the game by filling[n]your stock with them.[e]

[dlg GENERIC_HELP_309]
[s]Evolve a member's[n]Persona into its[n]Ultimate form.[e]

[dlg UnitMenuName]
Select Party Member[w][e]

[sel UnitSelect]
Joker[e]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]
Yoshizawa[e]

[sel UnitSelect2]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]
Kasumi[e]
Black Mask[e]
Sumire[e]

[sel UnitSelect3]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]
Yoshizawa[e]
All[e]

[dlg PersonaDelPrompt [Delete Personas]]
This will permanently remove all 
[n]Personas in your stock. Are you sure?[w][e]

[dlg UnitPrompt [Add Skill]]
Choose a character to add a skill to
[n]their currently equipped Persona.[w][e]

[dlg SkillPrompt [Add Skill]]
Enter the ID of the skill to add.
[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg PersonaAddPrompt [Add Persona]]
Input the ID of the Persona to add.
[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg NPCPrompt [Model Select]]
Set the first (4 digits) of the NPC
[n]filename to load. ([clr 2]○ button[clr 0] to end)[w][e]

[dlg NPCPrompt2 [Model Select]]
Set the next (3 digits) of the NPC
[n]model filename to load. ([clr 2]○ button[clr 0] to end)[w][e]

[dlg NPCPrompt3 [Model Select]]
Set the last (2 digits) of the NPC
[n]model filename to load. ([clr 2]○ button[clr 0] to end)[w][e]

[dlg GapPrompt [Animation Test]]
Select the GAP ID.
[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg GapPrompt2 [Animation Test]]
Select which animation to play.
[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg GapPrompt3 [Animation Test]]
Select whether to loop or not.[w][e]

[dlg GapPrompt4 [Animation Test]]
Select the third parameter.
[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg GapPrompt5 [Animation Test]]
Select the animation speed. Default is 10.
[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg GapPrompt6 [Animation Test]]
Select the number of seconds to play.[w][e]

[dlg CameraPrompt [Camera Mode]]
Use the D-Pad to manipulate the camera.
[n]Press [clr 4]△ button[clr 0] to quit.
[n](Camera must be locked first!)[w][e]

[dlg SelectBgmDialog [Ultimate DJ TGE]]
Select a bgm to play.[w][e]

[dlg FlagMenuName]
Flag Options[w][e]

[sel FlagMenu]
HUD Display[f 4 26 0 331][e]
Manage Party Members[f 4 26 1 332][e]
Change Romance Route[f 4 26 2 333][e]
Manage Hideout[f 4 26 3 334][e]
Room Editor[f 4 26 4 335][e]
Manual Input[f 4 26 5 336][e]
3rd Semester Stuff[f 4 26 6 337][e]
Mass Flag Editor[f 4 26 7 338][e]

[dlg GENERIC_HELP_331]
[s]Show/hide UI elements[n]such as date, time,[n]and missions.[e]

[dlg GENERIC_HELP_332]
[s]Add/remove party[n]members or change[n]the navi.[e]

[dlg GENERIC_HELP_333]
[s]Start or end a[n]relationship with a[n]female Confidant.[e]

[dlg GENERIC_HELP_334]
[s]Change the location[n]of the hideout.[e]

[dlg GENERIC_HELP_335]
[s]Modify the protag's[n]bedroom in the[n]Leblanc attic.[e]

[dlg GENERIC_HELP_336]
[s]Enter 5-digit decimal[n]ID of a bit to[n]enable or disable.[e]

[dlg GENERIC_HELP_337]
[s]Change values related[n]to Royal content.[e]

[dlg GENERIC_HELP_338]
[s]Manipulate a selected[n]range of bit flags to[n]toggle or print.[e]

[dlg PartyFlagMenuName]
Party Flags[e]

[sel PartyFlagMenu]
Add Party Members[f 4 26 0 341][e]
Remove Party Members[f 4 26 1 342][e]
Enable Party Editing[f 4 26 2 343][e]
Add Overworld Follower[f 4 26 3 344][e]
Toggle Showtimes[f 4 26 4 345][e]
Change Navigator[f 4 26 5 346][e]

[dlg GENERIC_HELP_341]
[s]Make a Persona user[n]available in the party.[e]

[dlg GENERIC_HELP_342]
[s]Revoke a Persona[n]user's availability in[n]your party.[e]

[dlg GENERIC_HELP_343]
[s]Allow choosing your[n]party from Stats in[n]the pause menu.[e]

[dlg GENERIC_HELP_344]
[s]Allow characters to[n]follow you around[n]in the field.[e]

[dlg GENERIC_HELP_345]
[s]Enable or disable[n]party member[n]Showtimes.[e]

[dlg GENERIC_HELP_346]
[s]Change which party[n]member currently serves[n]as Navigator.[e]

[dlg FieldMenuName]
Field Select[e]

[sel FieldMenu]
Enter Field ID[f 4 26 0 349][e]
Load Field[f 4 26 1 350][e]
Reload Current Field[f 4 26 2 351][e]

[dlg GENERIC_HELP_349]
[s]Input the 6 digits of a[n][clr 9]field pack's[clr 0] filename[n](ps4R.cpk/field)[e]

[dlg GENERIC_HELP_350]
[s]Attempt to load the [n]field. [clr 9]WARNING: Some[n]softlock the game.[clr 0][e]

[dlg GENERIC_HELP_351]
[s]Reload the field that[n]you're currently on.[e]

[dlg EventMenuName]
Event Select[e]

[sel EventMenu]
Enter Event ID[f 4 26 0 354][e]
Load Event[f 4 26 1 355][e]
Enter KeyFree Event ID[f 4 26 2 356][e]
Load KeyFree Event[f 4 26 3 357][e]

[dlg GENERIC_HELP_354]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](dataR.cpk/event)[e]

[dlg GENERIC_HELP_355]
[s]Attempt to load the[n]event. [clr 9]WARNING: Some[n]softlock the game.[clr 0][e]

[dlg GENERIC_HELP_356]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](ps4R.cpk/field).[clr 0][e]

[dlg GENERIC_HELP_357]
[s]Attempt to load a[n]KeyFree event.[n][clr 9]May softlock.[clr 0][e]

[dlg NaviMenuName]
Select Navigator[w][e]

[sel NaviMenu]
Morgana[e]
Futaba[e]
Akechi[e]
None[e]

[dlg HideoutMenuName]
Select Hideout[w][e]

[sel HideoutMenu]
School Rooftop[e]
Shibuya Walkway[e]
Leblanc Floor 2[e]
Leblanc Floor 1[e]

[dlg ShowtimeMenuName]
Toggle Showtimes[w][e]

[sel ShowtimeMenu]
Ann/Mona[e]
Morgana/Haru[e]
Ann/Yusuke[e]
Ryuji/Yusuke[e]
Ryuji/Makoto[e]
Joker/Akechi[e]
Makoto/Haru[e]
Joker/Kasumi[e]

[dlg ThirdSemesterMenuName]
3rd Semester Flags[w][e]

[sel ThirdSemesterMenu]
Sumire Name (Party)[e]
Sumire Route (Coop)[e]
Sumire Appearance[e]

[sel DateDisplayDlg]
Enable[e]
Disable[e]

[dlg LoveMenuName]
Select Relationship[w][e]

[sel LoveMenu]
Makoto[e]
Haru[e]
Ann[e]
Futaba[e]
Chihaya[e]
Takemi[e]
Kawakami[e]
Ohya[e]
Hifumi[e]
Sumire[e]

[dlg AboutDlg[About this menu]]
Created by [clr 6]ShrineFox[clr 0] using [clr 1]TGE[clr 0]'s
[n][clr 1]Atlus-Script-Tools[clr 0].
[n]github.com/tge-was-taken/Atlus-Script-Tools[w][e]
Special thanks to [clr 1]@regularpanties[clr 0]
[n]for providing a 6.72 PS4 for testing and
[n][clr 9]RayFirefist[clr 0] for initial P5R dev.[w][e]
Visit [clr 1]shrinefox.com[clr 0] for
[n]more information![w][e]

[sel RoomEdit]
Furniture[e]
Collectibles[e]
Cleanliness[e]

[sel FurnEdit]
Plant[e]
Sayuri[e]
DVD Player[e]
Game Console[e]
Old TV Set[e]
Radio[e]
Cat Bed[e]
UFO Game Prizes...[e]

[sel CollEdit]
Swan Boat[e]
Ramen[e]
Pennant[e]
Statue[e]
Sky Tree[e]
Big Hera[e]
Shumai[e]
Fusen[e]
I Love[e]
Idol[e]
More...[e]

[sel CollEdit2]
Seiza[e]
Syogi[e]
Hero[e]
Hamaya[e]
Jyainyan[e]
Sushi[e]
Choco[e]
Kumade[e]
Prev...[e]

[sel CleanEdit]
Bookshelf[e]
Workbench[e]
Visitor Table[e]
Training Chair[e]
Winter Heater[e]
Laptop[e]

[dlg MonthMenuName]
Select a Month[e]

[sel MonthMenu]
January[e]
February[e]
March[e]
April[e]
May[e]
June[e]
July[e]
August[e]
September[e]
October[e]
November[e]
December[e]

[dlg CalendarError]
Invalid day selected.[n]
Please try again.[w][e]

[dlg CalendarBackwardsError]
You can only go back one day at a time.[w][e]

[dlg BossTypeName]
Palace Boss Select[w][e]

[sel BossType]
Manual Entry[w][e]
By Palace[w][e]

[dlg SelectBossName]
Boss Event Select[w][e]

[sel Palace1]
Battle Scenario 1[e]
Battle with Morgana[e]
Battle Scenario 2[e]
Battle Scenario 3[e]
Sub Battle 1[e]
Sub Battle 2[e]
Gun Tutorial[e]
Hold Up Tutorial[e]
All Out Attack Tutorial[e]
Persona Recruit Tutorial[e]
Mini Boss 1[e]
Mini Boss 2[e]
Shadow Kamoshida[e]

[sel Palace2]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Battle Scenario[e]
Shadow Madarame[e]

[sel Palace3]
Battle Scenario[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Mini Boss 5[e]
Shadow Kaneshiro[e]

[sel Palace4]
Bandit[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Shadow Wakaba[e]

[sel Palace5]
Cognitive Sugimura[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Shadow Okumura[e]

[sel Palace6]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3 (05_B)[e]
Mini Boss 4 (05_BOSS)[e]
Akechi's First Battle[e]
Mini Boss (Dark Zone)[e]
Mini Boss (Camera Room)[e]
Mini Boss (Dice)[e]
Slot (ENYRY) Battle[e]
Escape Battle[e]
Shadow Sae[e]

[sel Palace7]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
First Target[e]
Second Target[e]
Third Target[e]
Fourth Target[e]
Fifth Target[e]
Akechi[e]
Shadow Shido[e]

[sel Palace8]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
The Holy Grail[e]
The Twins[e]
Uriel[e]
Raphael[e]
Gabriel[e]
Michael[e]
Yaldabaoth[e]

[sel Misc1]
Prologue Battle[e]
QUEST_BATTLE[e]
Yusuke Co-op[e]
int_CLEAR[e]
ALERT_CLEAR_EX[e]
PALACE_CLEAR_SYS[e]
PALACE_CALL_CALENDAR[e]
Closest encounter to position[e]
D_ENCOUNT_START[e]
dungeon_return_calendar[e]
dungeon_return[e]
Next[e]

[sel Misc2]
dungeon_exit_time_set[e]
dungeon_start_format[e]
DUNGEON_START_SAVE[e]
result_counter_clear[e]
MVP_CHOICE (CRASH!)[e]
D_ENCOUNT_NO_GET[e]
Dummy[e]
Dummy[e]
Previous[e]

[dlg HudTest1]
HUD has been enabled.[w][e]

[dlg HudTest2]
HUD has been disabled.[w][e]

[dlg PersonaAdded]
The chosen Persona has been[n]added to your stock.[w][e]

[dlg PersonaDeleted]
All Personas have been deleted.[w][e]

[dlg WeatherChanged]
Weather has been changed.[w][e]

[dlg LoadCheckError]
Set the required parameters[n]before attempting to load![w][e]

[dlg WeatherMenuName]
Weather Select[w][e]

[sel WeatherMenu]
Sunny[e]
Rainy[e]
Cloudy[e]
Snow[e]
Rainy Season[e]
Typhoon Warning[e]
Sunny Pollen Warning[e]
Cloudy Pollen Warning[e]
Torrential Rain[e]
Sunny Heatwave/Hot Night[e]
Sunny Flu Season[e]
Cloudy Flu Season[e]

[dlg BattleTypeName]
Battle Type Select[w][e]

[sel BattleTypeMenu]
Regular Encounter[e]
Boss Encounter[e]
Event Battle[e]

[dlg EventBattleName]
Battle Type Select[w][e]

[sel PalaceMenu]
Castle[e]
Art Museum[e]
First World Bank[e]
Pyramid[e]
Space Station[e]
Casino[e]
Cruise Ship[e]
Mementos Depths[e]
Misc[e]

[dlg PalaceName]
Palace Select[e]

[sel EventBattleSelect]
Akechi[e]
Akechi Phase 2[e]
Holy Grail[e]
Yaldabaoth[e]
Velvet Twins[e]
MISC[e]

[dlg EncounterPrompt]
Set the number of the encounter[n]you want to fight (4 digits).[w][e]

[sel FlagMassEditor]
Disable all flags[e]
Enable all flags[e]
Swap enabled/disabled flags[e]
Toggle range of flags[e]
Clear Inherit Data[e]

[dlg PersonaAddSkillMenuName]
Persona Options[w][e]

[sel PersonaAddSkillMenu]
Add Skill[e]
Add Skill (Manual Input)[e]

[dlg PersonaAddMenuName]
Persona Options[w][e]

[sel PersonaAddMenu]
Add Persona[e]
Add Persona (Manual Input)[e]

[dlg BagShowHide]
The bag has been toggled.[n]To see the change, go to a new field[n]or reload the current one.[w][e]

[dlg GENERIC_HELP_413]
Removes swaying effect[n]of the camera used[n]in dungeons.[w][e]

[dlg GENERIC_HELP_414]
Select an item's model ID to[n]spawn it and connect it to[n]the character's model.[w][e]

[dlg GENERIC_HELP_415]
Select a range of flags[n]to either enable or disable.[w][e]

[dlg ItemSpawnPrompt]
Enter the first half of the model's[n]ID from dataR.cpk/model/item.[n](4 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg ItemSpawnPrompt2]
Enter the last half of the model's[n]ID from dataR.cpk/model/item.[n](3 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg ObjectSpawnPrompt]
Enter the first half of the[n]model's ID from dataR.cpk/model/field_tex/object.[n](3 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg ObjectSpawnPrompt2]
Enter the last half of the[n]model's ID from dataR.cpk/model/field_tex/object.[n](3 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg FlagRangePrompt]
Enter the start of the[n]range to narrow down.[n](5 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg FlagRangePrompt2]
Enter the end of the[n]range to narrow down.[n](5 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg GENERIC_HELP_422]
Unlocks all Personas in the[n]Compendium. [clr 9]This will delete all[n]Personas in your current stock![clr 0][w][e]

[dlg MoviePlayPrompt[Movie Select]]
Insert the Movie ID to play.[n](3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg ManualBossFightPrompt[Movie Select]]
Insert the Boss ID to play.[n](2 digits, [clr 2]○ button[clr 0] to end)[w][e]